"""
Shared fixtures and config for the validation gate tests.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

# Ensures `lib.plcopen_validation` is importable (python/ on sys.path)
PYTHON_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PYTHON_ROOT))

FIXTURES_DIR = Path(__file__).parent / "fixtures"
BUGS_DIR = FIXTURES_DIR / "bugs"


@pytest.fixture(scope="session")
def fixtures_dir() -> Path:
    return FIXTURES_DIR


@pytest.fixture(scope="session")
def bugs_dir() -> Path:
    return BUGS_DIR


@pytest.fixture(scope="session")
def valid_xml_path() -> Path:
    """Synthetic multi-POU project — golden fixture (generated by scripts/gen-synthetic-fixture.mjs)."""
    return FIXTURES_DIR / "synthetic-project-valid.xml"
