/**
 * PLC Code Generation Tools
 * Tools for creating Function Blocks, Programs, Data Types, GVLs.
 */

import { z } from 'zod';
import { writeFile } from 'fs/promises';
import { join } from 'path';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import {
  buildPouXml,
  buildDataTypeXml,
  buildGvlXml,
  buildGvlStCode,
  type VarDeclaration,
  type PouDefinition,
  type DataTypeDefinition,
  type GvlDefinition,
} from '../utils/xml-builder.js';
import { validatePath, ensureDir } from '../utils/path-validation.js';
import { successResponse, errorResponse, getErrorMessage } from '../utils/mcp-helpers.js';
import { ensurePrefix, ensureDutPrefix } from '../utils/naming.js';
import { appendNextStep } from '../utils/next-steps.js';
import { log } from '../utils/logger.js';

/**
 * IEC 61131-3 identifier rule (§2.1.2): letter or _ followed by
 * letters/digits/_. Applies to zod schemas of tools that generate XML —
 * F3-063: prevents names that break XML 1.0 Name production.
 */
const IEC_IDENT_REGEX = /^[A-Za-z_][A-Za-z0-9_]*$/;
const IEC_IDENT_MSG = 'IEC 61131-3 identifier must start with letter/_ and contain only [A-Za-z0-9_]';

const VarSchema = z.object({
  name: z.string().min(1).regex(IEC_IDENT_REGEX, IEC_IDENT_MSG).describe('Variable name (Hungarian notation: bEnable, nState, rPos)'),
  type: z.string().min(1).describe('IEC 61131-3 type: BOOL, INT, DINT, REAL, LREAL, TIME, STRING, or derived name'),
  initialValue: z.string().optional().describe('Initial value (e.g., "0", "FALSE", "T#1S")'),
  comment: z.string().optional().describe('Variable description (English)'),
});

const DataTypeMemberSchema = z.object({
  name: z.string().min(1).regex(IEC_IDENT_REGEX, IEC_IDENT_MSG).describe('Member name'),
  type: z.string().optional().describe('Type (for struct members)'),
  value: z.string().optional().describe('Value (for enum members)'),
  comment: z.string().optional().describe('Description'),
});

/** Generation header for .st files */
function generationHeader(): string {
  const ts = new Date().toISOString().replace(/\.\d{3}Z$/, '');
  return `(* Generated by FestoCodesysMCP v1.0 — ${ts} *)`;
}

const END_KEYWORDS: Record<string, string> = {
  'FUNCTION_BLOCK': 'END_FUNCTION_BLOCK',
  'PROGRAM': 'END_PROGRAM',
  'FUNCTION': 'END_FUNCTION',
};

export function buildStFile(
  pouType: string,
  name: string,
  description: string,
  inputVars?: z.infer<typeof VarSchema>[],
  outputVars?: z.infer<typeof VarSchema>[],
  inOutVars?: z.infer<typeof VarSchema>[],
  localVars?: z.infer<typeof VarSchema>[],
  stCode?: string,
): string {
  const lines: string[] = [];
  lines.push(generationHeader());
  lines.push(`// ${name} — ${description}`);
  lines.push('');
  lines.push(`${pouType} ${name}`);

  const addVars = (section: string, vars?: z.infer<typeof VarSchema>[]) => {
    if (!vars || vars.length === 0) return;
    lines.push(section);
    for (const v of vars) {
      let line = `    ${v.name} : ${v.type}`;
      if (v.initialValue !== undefined && v.initialValue !== '') line += ` := ${v.initialValue}`;
      line += ';';
      if (v.comment) line += ` // ${v.comment}`;
      lines.push(line);
    }
    lines.push('END_VAR');
  };

  addVars('VAR_INPUT', inputVars);
  addVars('VAR_OUTPUT', outputVars);
  addVars('VAR_IN_OUT', inOutVars);
  addVars('VAR', localVars);

  if (stCode) {
    // Addresses P1-003 (Phase 4 audit): rejects stCode containing terminators
    // or keywords that start a new POU — prevents "code injection"
    // when concatenating stCode into the .st file. CODESYS rejects compilation with
    // orphan blocks, but the check gives explicit feedback to the caller.
    const terminalRe = /\b(END_FUNCTION_BLOCK|END_PROGRAM|END_FUNCTION|FUNCTION_BLOCK|PROGRAM|FUNCTION)\b/i;
    const match = stCode.match(terminalRe);
    if (match) {
      throw new Error(
        `Invalid stCode: contains POU-level keyword "${match[0]}" — stCode must be the body only, not a full POU definition.`,
      );
    }
    lines.push('');
    lines.push(stCode);
  }

  lines.push('');
  lines.push(END_KEYWORDS[pouType] || `END_${pouType}`);
  return lines.join('\n');
}

export function registerPlcCodeTools(server: McpServer) {

  // ── create_function_block ───────────────────────────────────────────
  server.registerTool(
    'create_function_block',
    {
      title: 'Create Function Block',
      description: `Generate a CODESYS Function Block (.st + PLCopen XML) with the standard interface built in.
USE WHEN: the user asks for a new FB and plc_library returned no reusable match.
ALWAYS BEFORE: (1) plc_library action=search — never create what already exists; (2) plc_knowledge topics 'conventions' + 'abbreviations'.
Standard pattern: bEnable/bExecute inputs, bDone/bBusy/bErr/nErrId outputs, nState state machine. Name auto-corrected to FB_ prefix.
DO NOT: use this for servo motion logic — motion uses MC_*_Festo blocks (topic 'festo-ptp'), not custom FBs.`,
      inputSchema: {
        name: z.string().min(1).regex(IEC_IDENT_REGEX, IEC_IDENT_MSG).describe('FB name (e.g., FB_ServoAxis or just ServoAxis)'),
        description: z.string().min(1).describe('What this FB does (English)'),
        inputVars: z.array(VarSchema).optional(),
        outputVars: z.array(VarSchema).optional(),
        inOutVars: z.array(VarSchema).optional(),
        localVars: z.array(VarSchema).optional(),
        stCode: z.string().describe('Structured Text body (the logic)'),
        outputDir: z.string().optional().describe('Output directory (default: cwd)'),
      },
      annotations: { destructiveHint: true, idempotentHint: false, readOnlyHint: false, openWorldHint: false },
    },
    async ({ name, description, inputVars, outputVars, inOutVars, localVars, stCode, outputDir }) => {
      try {
        const { name: fbName, corrected } = ensurePrefix(name, 'FB_');
        const dir = outputDir || process.cwd();
        const pathErr = validatePath(dir);
        if (pathErr) return errorResponse(`Error: ${pathErr}`);
        await ensureDir(dir);

        const st = buildStFile('FUNCTION_BLOCK', fbName, description,
          inputVars, outputVars, inOutVars, localVars, stCode);
        const stPath = join(dir, `${fbName}.st`);
        await writeFile(stPath, st, 'utf-8');

        const pou: PouDefinition = {
          name: fbName, pouType: 'functionBlock',
          inputVars: inputVars as VarDeclaration[],
          outputVars: outputVars as VarDeclaration[],
          inOutVars: inOutVars as VarDeclaration[],
          localVars: localVars as VarDeclaration[],
          body: stCode || '',
        };
        const xml = buildPouXml(pou);
        const xmlPath = join(dir, `${fbName}.xml`);
        await writeFile(xmlPath, xml, 'utf-8');

        log('info', 'create_function_block', `Created ${fbName} at ${dir}`);

        const note = corrected ? `\nNote: Name auto-corrected to "${fbName}" (FB_ prefix required).\n` : '';
        return successResponse(appendNextStep(
          `Created:${note}\n  ST:  ${stPath}\n  XML: ${xmlPath}\n\nImport in CODESYS: Project → Import PLCopen XML...`,
          'create_function_block',
        ));
      } catch (err) {
        return errorResponse(`Error creating function block "${name}": ${getErrorMessage(err)}`);
      }
    }
  );

  // ── create_program ──────────────────────────────────────────────────
  server.registerTool(
    'create_program',
    {
      title: 'Create Program (PRG)',
      description: `Generate a CODESYS Program (.st + PLCopen XML) for cyclic control logic.
USE WHEN: you need a cyclic PRG (runs once per scan) — PRG_Main, PRG_Auto, sequence orchestration — and no reusable one exists.
Programs run once per PLC scan (PRG_Main, PRG_Auto, etc.). Name auto-corrected to PRG_ prefix if missing.`,
      inputSchema: {
        name: z.string().min(1).regex(IEC_IDENT_REGEX, IEC_IDENT_MSG).describe('Program name (e.g., PRG_Main or just Main)'),
        description: z.string().min(1).describe('What this program does'),
        localVars: z.array(VarSchema).optional(),
        stCode: z.string().describe('Structured Text body'),
        outputDir: z.string().optional().describe('Output directory (default: cwd)'),
      },
      annotations: { destructiveHint: true, idempotentHint: false, readOnlyHint: false, openWorldHint: false },
    },
    async ({ name, description, localVars, stCode, outputDir }) => {
      try {
        const { name: prgName, corrected } = ensurePrefix(name, 'PRG_');
        const dir = outputDir || process.cwd();
        const pathErr = validatePath(dir);
        if (pathErr) return errorResponse(`Error: ${pathErr}`);
        await ensureDir(dir);

        const st = buildStFile('PROGRAM', prgName, description,
          undefined, undefined, undefined, localVars, stCode);
        await writeFile(join(dir, `${prgName}.st`), st, 'utf-8');

        const pou: PouDefinition = {
          name: prgName, pouType: 'program',
          localVars: localVars as VarDeclaration[],
          body: stCode || '',
        };
        const xml = buildPouXml(pou);
        await writeFile(join(dir, `${prgName}.xml`), xml, 'utf-8');

        log('info', 'create_program', `Created ${prgName} at ${dir}`);

        const note = corrected ? `\nNote: Name auto-corrected to "${prgName}" (PRG_ prefix required).\n` : '';
        return successResponse(appendNextStep(
          `Created:${note}\n  ST:  ${join(dir, prgName)}.st\n  XML: ${join(dir, prgName)}.xml`,
          'create_program',
        ));
      } catch (err) {
        return errorResponse(`Error creating program "${name}": ${getErrorMessage(err)}`);
      }
    }
  );

  // ── create_data_type ────────────────────────────────────────────────
  server.registerTool(
    'create_data_type',
    {
      title: 'Create Data Type (ENUM/STRUCT)',
      description: `Generate a CODESYS data type: ENUM (E_*) or STRUCT (ST_*), with .st + PLCopen XML output.
USE WHEN: you need an ENUM (state/mode) or STRUCT (config/record) to back FB, GVL, or program declarations.
Name auto-corrected to E_ (enum) or ST_ (struct) prefix if missing.`,
      inputSchema: {
        name: z.string().min(1).regex(IEC_IDENT_REGEX, IEC_IDENT_MSG).describe('Type name (e.g., E_MachState or MachState, ST_AxisCfg or AxisCfg)'),
        kind: z.enum(['enum', 'struct']),
        members: z.array(DataTypeMemberSchema).min(1),
        outputDir: z.string().optional().describe('Output directory (default: cwd)'),
      },
      annotations: { destructiveHint: true, idempotentHint: false, readOnlyHint: false, openWorldHint: false },
    },
    async ({ name, kind, members, outputDir }) => {
      try {
        const { name: dtName, corrected } = ensureDutPrefix(name, kind);
        const dir = outputDir || process.cwd();
        const pathErr = validatePath(dir);
        if (pathErr) return errorResponse(`Error: ${pathErr}`);
        await ensureDir(dir);

        const lines: string[] = [];
        lines.push(generationHeader());
        lines.push(`TYPE ${dtName} :`);
        if (kind === 'enum') {
          lines.push('(');
          members.forEach((m, i) => {
            let line = `    ${m.name}`;
            if (m.value !== undefined) line += ` := ${m.value}`;
            if (i < members.length - 1) line += ',';
            if (m.comment) line += ` // ${m.comment}`;
            lines.push(line);
          });
          lines.push(');');
        } else {
          lines.push('STRUCT');
          for (const m of members) {
            let line = `    ${m.name} : ${m.type || 'INT'};`;
            if (m.comment) line += ` // ${m.comment}`;
            lines.push(line);
          }
          lines.push('END_STRUCT');
        }
        lines.push('END_TYPE');

        await writeFile(join(dir, `${dtName}.st`), lines.join('\n'), 'utf-8');

        const dt: DataTypeDefinition = {
          name: dtName, kind,
          members: members as DataTypeDefinition['members'],
        };
        await writeFile(join(dir, `${dtName}.xml`), buildDataTypeXml(dt), 'utf-8');

        log('info', 'create_data_type', `Created ${dtName} (${kind}) at ${dir}`);

        const note = corrected ? `\nNote: Name auto-corrected to "${dtName}" (${kind === 'enum' ? 'E_' : 'ST_'} prefix required).\n` : '';
        return successResponse(appendNextStep(
          `Created:${note}\n  ST:  ${join(dir, dtName)}.st\n  XML: ${join(dir, dtName)}.xml`,
          'create_data_type',
        ));
      } catch (err) {
        return errorResponse(`Error creating data type "${name}": ${getErrorMessage(err)}`);
      }
    }
  );

  // ── create_gvl ──────────────────────────────────────────────────────
  server.registerTool(
    'create_gvl',
    {
      title: 'Create Global Variable List',
      description: `Generate a Global Variable List (.st + PLCopen XML) with {attribute 'qualified_only'}.
USE WHEN: you need globals shared across POUs — I/O map, system flags, HMI tags (GVL_HMI), config.
Name auto-corrected to GVL_ prefix if missing. Common: GVL_Sys, GVL_IO, GVL_HMI, GVL_Cfg.`,
      inputSchema: {
        name: z.string().min(1).regex(IEC_IDENT_REGEX, IEC_IDENT_MSG).describe('GVL name (e.g., GVL_Sys or just Sys)'),
        variables: z.array(VarSchema).min(1),
        isConstant: z.boolean().default(false),
        outputDir: z.string().optional().describe('Output directory (default: cwd)'),
      },
      annotations: { destructiveHint: true, idempotentHint: false, readOnlyHint: false, openWorldHint: false },
    },
    async ({ name, variables, isConstant, outputDir }) => {
      try {
        const { name: gvlName, corrected } = ensurePrefix(name, 'GVL_');
        const dir = outputDir || process.cwd();
        const pathErr = validatePath(dir);
        if (pathErr) return errorResponse(`Error: ${pathErr}`);
        await ensureDir(dir);

        const gvl: GvlDefinition = {
          name: gvlName,
          variables: variables as VarDeclaration[],
          isConstant,
        };

        // Use buildGvlStCode as single source of truth for ST content
        const stContent = `${generationHeader()}\n{attribute 'qualified_only'}\n${buildGvlStCode(gvl)}`;
        await writeFile(join(dir, `${gvlName}.st`), stContent, 'utf-8');
        await writeFile(join(dir, `${gvlName}.xml`), buildGvlXml(gvl), 'utf-8');

        log('info', 'create_gvl', `Created ${gvlName} at ${dir}`);

        const note = corrected ? `\nNote: Name auto-corrected to "${gvlName}" (GVL_ prefix required).\n` : '';
        return successResponse(appendNextStep(
          `Created:${note}\n  ST:  ${join(dir, gvlName)}.st\n  XML: ${join(dir, gvlName)}.xml`,
          'create_gvl',
        ));
      } catch (err) {
        return errorResponse(`Error creating GVL "${name}": ${getErrorMessage(err)}`);
      }
    }
  );
}
